# Generated by Django 3.2.9 on 2021-11-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compound_name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('up_date', models.DateTimeField(auto_now_add=True)),
                ('created_img', models.ImageField(blank=True, upload_to='imagesCompound/')),
            ],
        ),
        migrations.CreateModel(
            name='Efectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efecto_name', models.CharField(max_length=200)),
                ('efecto_description', models.TextField(blank=True)),
                ('efecto_codigo', models.TextField(blank=True)),
                ('efecto_value1', models.IntegerField(blank=True)),
                ('efecto_value2', models.IntegerField(blank=True)),
                ('efecto_value3', models.IntegerField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('up_date', models.DateTimeField(auto_now_add=True)),
                ('zindex', models.IntegerField(default=1)),
                ('compound', models.ManyToManyField(blank=True, to='creator.Compound')),
            ],
        ),
        migrations.CreateModel(
            name='UpImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('up_date', models.DateTimeField(auto_now_add=True)),
                ('upload_img', models.ImageField(upload_to='imagesLayers/')),
                ('rarity', models.IntegerField(choices=[(50, 'Normal'), (40, 'Medium'), (5, 'Rare'), (4, 'Superrare'), (1, 'Unique')])),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('file_size_w', models.IntegerField(blank=True, default=2000)),
                ('file_size_h', models.IntegerField(blank=True, default=2000)),
                ('active', models.BooleanField(default=True)),
                ('up_date', models.DateTimeField(auto_now_add=True)),
                ('project_layers', models.ManyToManyField(blank=True, to='creator.Layer')),
            ],
        ),
        migrations.CreateModel(
            name='groupImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupImage_name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('up_date', models.DateTimeField(auto_now_add=True)),
                ('layer_images', models.ManyToManyField(blank=True, to='creator.UpImage')),
            ],
        ),
        migrations.AddField(
            model_name='compound',
            name='group_images',
            field=models.ManyToManyField(blank=True, to='creator.groupImage'),
        ),
        migrations.AddField(
            model_name='compound',
            name='up_images',
            field=models.ManyToManyField(blank=True, to='creator.UpImage'),
        ),
    ]
