# Generated by Django 3.2.9 on 2021-11-25 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Efectos',
            new_name='Efecto',
        ),
    ]
